using System.Diagnostics.CodeAnalysis;
using AutoFixture.AutoNSubstitute;
using AutoFixture.Xunit2;
using Xunit;

namespace Atc.TestTools
{
    /// <summary>
    /// Provides a data source for a data theory, with the data coming from inline values
    /// combined with auto-generated data specimens generated by AutoFixture and NSubstitute.
    /// </summary>
    /// <remarks>
    /// NSubstitute is used when the type is abstract, or when the <see cref="SubstituteAttribute"/> is applied.
    /// </remarks>
    [SuppressMessage(
            "Design",
            "CA1019:Define accessors for attribute arguments",
            Justification = "By design")]
    public sealed class InlineAutoNSubstituteDataAttribute : CompositeDataAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineAutoNSubstituteDataAttribute"/> class.
        /// </summary>
        public InlineAutoNSubstituteDataAttribute([NotNull] params object[] values)
            : base(new InlineDataAttribute(values), new AutoNSubstituteDataAttribute())
        {
        }
    }
}