namespace Atc.Test.Customizations;

/// <summary>
/// Enables generation of the immutable collection types in
/// <see cref="System.Collections.Immutable"/>, which AutoFixture cannot create
/// out of the box because they have no public constructor.
/// </summary>
/// <remarks>
/// Each supported immutable type is generated by first resolving a populated mutable
/// counterpart (for example <see cref="List{T}"/> for <see cref="ImmutableArray{T}"/>)
/// and then converting it, so the resulting collections follow the same population
/// rules as any other generated collection.
/// <para>
/// Supported: <see cref="ImmutableArray{T}"/>, <see cref="ImmutableList{T}"/>,
/// <see cref="ImmutableDictionary{TKey,TValue}"/>, <see cref="ImmutableHashSet{T}"/>,
/// <see cref="ImmutableSortedSet{T}"/> and
/// <see cref="ImmutableSortedDictionary{TKey,TValue}"/>.
/// </para>
/// </remarks>
[AutoRegister]
public class ImmutableObjectCustomization : ICustomization
{
    /// <inheritdoc/>
    public void Customize(IFixture fixture)
    {
        fixture.Customizations.Add(
            new ImmutableObjectBuilder(
                typeof(ImmutableArray<>),
                typeof(List<>),
                o => ImmutableArray.ToImmutableArray(o)));

        fixture.Customizations.Add(
            new ImmutableObjectBuilder(
                typeof(ImmutableList<>),
                typeof(List<>),
                o => ImmutableList.ToImmutableList(o)));

        fixture.Customizations.Add(
            new ImmutableObjectBuilder(
                typeof(ImmutableDictionary<,>),
                typeof(Dictionary<,>),
                o => ImmutableDictionary.ToImmutableDictionary(o)));

        fixture.Customizations.Add(
            new ImmutableObjectBuilder(
                typeof(ImmutableHashSet<>),
                typeof(HashSet<>),
                o => ImmutableHashSet.ToImmutableHashSet(o)));

        fixture.Customizations.Add(
            new ImmutableObjectBuilder(
                typeof(ImmutableSortedSet<>),
                typeof(SortedSet<>),
                o => ImmutableSortedSet.ToImmutableSortedSet(o)));

        fixture.Customizations.Add(
            new ImmutableObjectBuilder(
                typeof(ImmutableSortedDictionary<,>),
                typeof(SortedDictionary<,>),
                o => ImmutableSortedDictionary.ToImmutableSortedDictionary(o)));
    }

    /// <summary>
    /// Creates instances of a single immutable collection type by resolving a mutable
    /// counterpart and converting it.
    /// </summary>
    /// <param name="immutableType">The open generic immutable type to handle, for example <c>typeof(ImmutableArray&lt;&gt;)</c>.</param>
    /// <param name="underlyingType">The open generic mutable type to resolve from the fixture.</param>
    /// <param name="converter">Converts the resolved mutable instance into the immutable one.</param>
    private sealed class ImmutableObjectBuilder(
        Type immutableType,
        Type underlyingType,
        Func<dynamic, object> converter)
        : ISpecimenBuilder
    {
        /// <inheritdoc/>
        public object Create(
            object request,
            ISpecimenContext context)
        {
            if (GetRequestType(request) is not { IsGenericType: true } type
                || type.GetGenericTypeDefinition() != immutableType
                || type.GetGenericArguments() is not { Length: > 0 } args)
            {
                return new NoSpecimen();
            }

            var listType = underlyingType.MakeGenericType(args);
            dynamic list = context.Resolve(listType);

            return converter.Invoke(list);
        }

        private static Type? GetRequestType(object request)
            => request switch
            {
                ParameterInfo pi => pi.ParameterType,
                Type t => t,
                _ => null,
            };
    }
}