namespace Atc.Test;

/// <summary>
/// Provides auto-generated data specimens generated by AutoFixture and NSubstitute
/// as an extension to xUnit.net's Theory attribute.
/// </summary>
/// <remarks>
/// NSubstitute is used when the type is abstract, or when the <see cref="SubstituteAttribute"/> is applied.
/// </remarks>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
public sealed class AutoNSubstituteDataAttribute : AutoDataAttribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="AutoNSubstituteDataAttribute"/> class.
    /// </summary>
    public AutoNSubstituteDataAttribute()
        : base(FixtureFactory.Create)
    {
    }
}