namespace Atc.Test;

/// <summary>
/// Provides a data source for a data theory, with the data coming from inline values
/// combined with auto-generated data specimens generated by AutoFixture and NSubstitute.
/// </summary>
/// <remarks>
/// NSubstitute is used when the type is abstract, or when the <see cref="SubstituteAttribute"/> is applied.
/// </remarks>
[SuppressMessage(
    "Design",
    "CA1019:Define accessors for attribute arguments",
    Justification = "By design")]
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
public sealed class InlineAutoNSubstituteDataAttribute : CompositeDataAttribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="InlineAutoNSubstituteDataAttribute"/> class.
    /// </summary>
    /// <param name="data">The data values to pass to the theory.</param>
    public InlineAutoNSubstituteDataAttribute([NotNull] params object[] data)
        : base(new InlineDataAttribute(data), new AutoNSubstituteDataAttribute())
    {
    }
}