using System.Diagnostics.CodeAnalysis;
using AutoFixture.Xunit2;
using Xunit;

namespace Atc.Test
{
    /// <summary>
    /// Provides a data source for a data theory, with the data coming from
    /// one of the following sources and combined with auto-generated data
    /// specimens generated by AutoFixture and NSubstitute:
    /// <list type="number">
    /// <item>A static property</item>
    /// <item>A static field</item>
    /// <item>A static method (with parameters)</item>
    /// </list>
    /// The member must return something compatible with
    /// IEnumerable&lt;object[]&gt; with the test data.
    /// </summary>
    [SuppressMessage(
        "Design",
        "CA1019:Define accessors for attribute arguments",
        Justification = "By design")]
    public sealed class MemberAutoNSubstituteDataAttribute : CompositeDataAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MemberAutoNSubstituteDataAttribute"/> class.
        /// </summary>
        /// <param name="memberName">The name of the public static member on the test
        /// class that will provide the test data.</param>
        public MemberAutoNSubstituteDataAttribute(string memberName)
            : base(
                new MemberDataAttribute(memberName),
                new AutoNSubstituteDataAttribute())
        {
        }
    }
}